config/routes.rb
Rails.application.routes.draw do
  resources :goals
  devise_for :users
  root to: 'reservations#index'
  resources :orders
  resources :reservations, only: [:new, :create, :show] do
    resources :menu_details, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/menu.rb
class Menu < ActiveHash::Base
  self.data = [
  { id: 1, name: '---', price: '0'},
  { id: 2, name: '季節のおまかせコース', price: '8800'},
  { id: 3, name: '海鮮鍋セットコース', price: '10800'},
  { id: 4, name: '季節のおまかせコース + 2時間飲み放題', price: '12800'},
  { id: 5, name: '海鮮鍋セットコース + 2時間飲み放題', price: '15000'}
  ]

  include ActiveHash::Associations
  has_many :reservations
end 

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_one :menu
  has_one_attached :image

  with_options presence: true do
    validates :menu, numericality: { other_than: 1}
    validates :date
    validates :time
    validates :user_id
    validates :people
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :reservation
  has_one :order

  with_options presence: true do
    validates :nickname
    validates :postal_code, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
    validates :prefecture
    validates :municipality
    validates :address
    validates :phone, format: {with: /\A0[0-9]{9,10}\z/ }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :phone, :postal_code, :prefecture, :municipality, :address, :building])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal, only: %i[ show edit update destroy ]

  # GET /goals or /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1 or /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = current_user.goals.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goal_params
      params.require(:goal).permit(:title, :user_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @menu = Menu.all
  end

  def new
    @reservation = Reservation.new
    @menu = Menu.all
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def reservation_params
    params.require(:reservation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/menu_details_helper.rb
module MenuDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.title %></td>
        <td><%= goal.user_id %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @goal.user_id %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Original</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1><%= link_to '商品購入フォーム', orders_path, class:'reservation-form'%></h1>

app/views/reservations/create.html.erb
<div class="success">
  <h3>予約が完了しました。<h3>
  <a class="btn" href="/">戻る</a>
</div>

app/views/reservations/index.html.erb
<html lang="ja">
  <head>
    <title>創作</title>
    <meta charset="utf-8">

    <meta name="description" content="テキストテキストテキストテキストテキストテキストテキストテキスト">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
 
    <%# <link rel="stylesheet" href="css/style.css"> %>
  </head>

  <body>
    <header id="header">
      <h1 class="site-title">
        <a href="/">想作和食 旬</a>
      </h1>

      <nav id="nav">
      
      <% if user_signed_in? %>
        <ul>
          <li><%= link_to "予約", new_reservation_path, method: :get %></li>
          <li><%= link_to "注文", orders_path, method: :get %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <a class="pagetop1" id="top" href=/reservations/new>お店のご予約はこちら</a> 
          <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
        </ul>
        
        <% end %>
      </nav>

      
    </header>


<% if user_signed_in? %>
    <main>
      <section id="news" class="wrapper">
      </section>
      <section id="products1" class="products wrapper">
        <h2 class="section-title">
          <span class="ja">ご注文</span>
        </h2>
        <div class="img">
          <a href=/reservations/new><img src="/assets/kaisen1.jpg" alt="購入">
          <p class="text">海鮮鍋セット (4人前)<br>¥12,800-</p></a>
        </div>
      </section>

      <section id="products2" class="products wrapper">
        
        <div class="img">
          <a href=/reservations/new><img src="/assets/motu.jpg" alt="購入">
          <p class="text">もつ鍋セット (4人前)<br>¥10,800-</p></a>
        </div>
      </section>

    </main>
<% end %>



 <script>
    const topLink = document.getElementById("top");
    window.addEventListener("scroll", () => {
      const scrollValue = document.scrollingElement.scrollTop;
      if (scrollValue >= 140) {
          topLink.style.display = "inline";
      } else if (scrollValue < 140) {
          topLink.style.display = "none";
      }
    });
</script>

app/views/reservations/new.html.erb
<h1><%= link_to '予約フォーム', root_path, class:'reservation-form'%></h1>
<%= form_with model: @reservation, url: new_reservation_path, method: :get, class: 'reservation', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
    <div class="reservation-price">
      <h2>コース選択</h2>

      <div calss="reservation-date">
        <%= f.label :日付を選択, class: 'label'%><br />
        <%= f.date_field :date, class: 'date' %>
      </div>

      <div class="reservation-time">
        <%= f.label :時間を選択, class: 'label' %><br />
        <%= f.time_field :time, class: 'time'%>
      </div>

      <div class="reservation-people">
        <%= f.label :人数%><br />
        <%= f.number_field :people, class: 'people'%>人
      </div>

      <%# 出力希望箇所 %>
      <div class="menu">
        コース<br /> 
        <%= f.select :menu_id, (Menu.all.map {|m| [m.name, m.id, {'data-price' => m.price }]}), {}, {id: 'menu_select'} %>
      </div>
      
      <div class="person-price">
        <span>1人当たりのお支払い</span><br />
        <span>
        <span id="person_price"></span>円 
        </span>
      </div>

      <div class="total-price">
      
        <span>合計金額</span><br />
        <span>
        <span id="total_price"></span>円
        </span>
        
      </div>
      <%# 出力希望箇所 %>

      <div class="reservation-remark">
        <%= f.label :その他%><br />
        <%= f.text_area :remark, placeholder:"嫌いな食べ物など",class: 'remark'%>
      </div>

    <div>
      <%= f.submit "予約する"%> <br />
    </div>

  <div class="reservation-btn">
    <%= link_to '戻る', root_path, class:'reservation-form'%> 
  </div>
  

  
  <script>
const menu_select = document.getElementById("menu_select");
menu_select.addEventListener('change', (event) => {
	const selected_index = menu_select.selectedIndex;
	const selected_option = menu_select.options[selected_index];
	const price = selected_option.getAttribute("data-price");
	const personPrice = document.getElementById("person_price").innerHTML = price;
	const people = document.getElementById("reservation_people");
	people.addEventListener("input", () => {
		document.getElementById("total_price").innerHTML = Math.floor(personPrice * parseInt(document.getElementById('reservation_people').value));
	})
});
</script>

<% end %> 

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>